### ISSUE TITLE
UTC unexpected behavior

### ISSUE THREAD

**Issue by jorgeamadosoria** [tcort/handlebars-dateformat#3]
The ternary comparison of the utc parameter allows the operator to effectively default to true.
{{dateFormat date "YYYY-MM-DD" true}} -> utc = true //acts like true
{{dateFormat date "YYYY-MM-DD" false}} -> utc = false //acts like false
{{dateFormat date "YYYY-MM-DD" ""}} -> utc = "" // acts like  false
{{dateFormat date "YYYY-MM-DD" "1"}} -> utc = "1" // acts like  true

{{dateFormat date "YYYY-MM-DD"}} -> utc = Object // acts like  true
Therefore defaults to utc mode. This is ok for my use case, but may not be desired and it is not what the readme.md says.

**Comment by tcort** [comment]
Thanks for catching this mistake. I've rolled out version `1.1.1` with a fix.

> The ternary comparison of the utc parameter allows the operator to effectively default to true.

Instead of a strict true, it did a [truthy](https://developer.mozilla.org/en/docs/Glossary/Truthy) check.

> {{dateFormat date "YYYY-MM-DD"}} -> utc = Object // acts like true
> Therefore defaults to utc mode.

It was a bad assumption on my part. I thought handlebars would be passing in `undefined` (defaulting to `false`). However, handlebars passes in an object as the last parameter which is truthy. My tests did not catch the mistake.

**Comment by jorgeamadosoria** [comment]
Thank you for getting back on this so fast. Keep up the good work!
